apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090 # 'prometheus' is the service name in docker-compose
    access: proxy
    isDefault: true
    editable: true
